/*! 
 * SAPUI5

		(c) Copyright 2009-2021 SAP SE. All rights reserved
	 
 */
(function(){function e(e,t,n){if(n){return t?t(e):e}if(!e||!e.then){e=Promise.resolve(e)}return t?e.then(t):e}function t(){}function n(e){var n=e();if(n&&n.then){return n.then(t)}}sap.ui.define(["../eventlogging/UserEvents","../eventlogging/EventConsumer","../suggestions/SuggestionType","sap/base/Log"],function(t,r,a,o){function c(e){return e&&e.__esModule&&typeof e.default!=="undefined"?e.default:e}function i(e,t){if(!(e instanceof t)){throw new TypeError("Cannot call a class as a function")}}function s(e,t){for(var n=0;n<t.length;n++){var r=t[n];r.enumerable=r.enumerable||false;r.configurable=true;if("value"in r)r.writable=true;Object.defineProperty(e,r.key,r)}}function u(e,t,n){if(t)s(e.prototype,t);if(n)s(e,n);Object.defineProperty(e,"prototype",{writable:false});return e}function l(e,t){if(typeof t!=="function"&&t!==null){throw new TypeError("Super expression must either be null or a function")}e.prototype=Object.create(t&&t.prototype,{constructor:{value:e,writable:true,configurable:true}});Object.defineProperty(e,"prototype",{writable:false});if(t)f(e,t)}function f(e,t){f=Object.setPrototypeOf?Object.setPrototypeOf.bind():function e(t,n){t.__proto__=n;return t};return f(e,t)}function h(e){var t=p();return function n(){var r=b(e),a;if(t){var o=b(this).constructor;a=Reflect.construct(r,arguments,o)}else{a=r.apply(this,arguments)}return g(this,a)}}function g(e,t){if(t&&(typeof t==="object"||typeof t==="function")){return t}else if(t!==void 0){throw new TypeError("Derived constructors may only return object or undefined")}return y(e)}function y(e){if(e===void 0){throw new ReferenceError("this hasn't been initialised - super() hasn't been called")}return e}function p(){if(typeof Reflect==="undefined"||!Reflect.construct)return false;if(Reflect.construct.sham)return false;if(typeof Proxy==="function")return true;try{Boolean.prototype.valueOf.call(Reflect.construct(Boolean,[],function(){}));return true}catch(e){return false}}function b(e){b=Object.setPrototypeOf?Object.getPrototypeOf.bind():function e(t){return t.__proto__||Object.getPrototypeOf(t)};return b(e)}function v(e,t,n){if(t in e){Object.defineProperty(e,t,{value:n,enumerable:true,configurable:true,writable:true})}else{e[t]=n}return e}
/*!
   * SAPUI5

		(c) Copyright 2009-2021 SAP SE. All rights reserved
	
   */var S=t["UserEventType"];var T=c(r);var E=c(a);var d=function(t){l(a,t);var r=h(a);function a(){var e;i(this,a);for(var t=arguments.length,n=new Array(t),c=0;c<t;c++){n[c]=arguments[c]}e=r.call.apply(r,[this].concat(n));v(y(e),"log",o.getLogger("sap.esh.search.ui.eventlogging.UsageAnalyticsConsumerFlp"));v(y(e),"actionPrefix","FLP: ");v(y(e),"label","FLP");return e}u(a,[{key:"initAsync",value:function t(){try{const t=this;var r,a;return e(n(function(){if((r=window.sap)!==null&&r!==void 0&&(a=r.ushell)!==null&&a!==void 0&&a.Container){return e(window.sap.ushell.Container.getServiceAsync("UsageAnalytics"),function(e){t.analytics=e})}}))}catch(e){return Promise.reject(e)}}},{key:"logEvent",value:function e(t){if(!this.analytics){return}switch(t.type){case S.RESULT_LIST_ITEM_NAVIGATE:this.analytics.logCustomEvent("".concat(this.actionPrefix,"Search"),"Launch Object",[t.targetUrl]);break;case S.RESULT_LIST_ITEM_ATTRIBUTE_NAVIGATE:this.analytics.logCustomEvent("".concat(this.actionPrefix,"Search"),"Launch Object",[t.targetUrl]);break;case S.SUGGESTION_SELECT:switch(t.suggestionType){case E.App:this.analytics.logCustomEvent("".concat(this.actionPrefix,"Search"),"Suggestion Select App",[t.suggestionTitle,t.targetUrl,t.searchTerm]);this.analytics.logCustomEvent("".concat(this.actionPrefix,"Application Launch point"),"Search Suggestions",[t.suggestionTitle,t.targetUrl,t.searchTerm]);break;case E.DataSource:this.analytics.logCustomEvent("".concat(this.actionPrefix,"Search"),"Suggestion Select Datasource",[t.dataSourceKey,t.searchTerm]);break;case E.Object:this.analytics.logCustomEvent("".concat(this.actionPrefix,"Search"),"Suggestion Select Object Data",[t.suggestionTerm,t.dataSourceKey,t.searchTerm]);break;case E.Recent:this.analytics.logCustomEvent("".concat(this.actionPrefix,"Search"),"Suggestion Select Object Data",[t.suggestionTerm,t.dataSourceKey,t.searchTerm]);break}break;case S.SEARCH_REQUEST:this.analytics.logCustomEvent("".concat(this.actionPrefix,"Search"),"Search",[t.searchTerm,t.dataSourceKey]);break;case S.RESULT_LIST_ITEM_NAVIGATE_CONTEXT:this.analytics.logCustomEvent("".concat(this.actionPrefix,"Search"),"Launch Related Object",[t.targetUrl]);break;case S.SUGGESTION_REQUEST:this.analytics.logCustomEvent("".concat(this.actionPrefix,"Search"),"Suggestion",[t.suggestionTerm,t.dataSourceKey]);break;case S.TILE_NAVIGATE:this.analytics.logCustomEvent("".concat(this.actionPrefix,"Search"),"Launch App",[t.tileTitle,t.targetUrl]);this.analytics.logCustomEvent("".concat(this.actionPrefix,"Application Launch point"),"Search Results",[t.tileTitle,t.targetUrl]);break}this.log.debug("[".concat(this.label,"] Logged user event ").concat(t.type))}}]);return a}(T);return d})})();
//# sourceMappingURL=UsageAnalyticsConsumerFlp.js.map