/*! 
 * SAPUI5

		(c) Copyright 2009-2021 SAP SE. All rights reserved
	 
 */
(function(){sap.ui.define(["./ResultSetItem","../core/core"],function(t,e){function r(t,e){var r=typeof Symbol!=="undefined"&&t[Symbol.iterator]||t["@@iterator"];if(!r){if(Array.isArray(t)||(r=n(t))||e&&t&&typeof t.length==="number"){if(r)t=r;var i=0;var a=function(){};return{s:a,n:function(){if(i>=t.length)return{done:true};return{done:false,value:t[i++]}},e:function(t){throw t},f:a}}throw new TypeError("Invalid attempt to iterate non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.")}var u=true,o=false,s;return{s:function(){r=r.call(t)},n:function(){var t=r.next();u=t.done;return t},e:function(t){o=true;s=t},f:function(){try{if(!u&&r.return!=null)r.return()}finally{if(o)throw s}}}}function n(t,e){if(!t)return;if(typeof t==="string")return i(t,e);var r=Object.prototype.toString.call(t).slice(8,-1);if(r==="Object"&&t.constructor)r=t.constructor.name;if(r==="Map"||r==="Set")return Array.from(t);if(r==="Arguments"||/^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(r))return i(t,e)}function i(t,e){if(e==null||e>t.length)e=t.length;for(var r=0,n=new Array(e);r<e;r++)n[r]=t[r];return n}function a(t,e){if(!(t instanceof e)){throw new TypeError("Cannot call a class as a function")}}function u(t,e){for(var r=0;r<e.length;r++){var n=e[r];n.enumerable=n.enumerable||false;n.configurable=true;if("value"in n)n.writable=true;Object.defineProperty(t,n.key,n)}}function o(t,e,r){if(e)u(t.prototype,e);if(r)u(t,r);Object.defineProperty(t,"prototype",{writable:false});return t}function s(t,e){if(typeof e!=="function"&&e!==null){throw new TypeError("Super expression must either be null or a function")}t.prototype=Object.create(e&&e.prototype,{constructor:{value:t,writable:true,configurable:true}});Object.defineProperty(t,"prototype",{writable:false});if(e)f(t,e)}function f(t,e){f=Object.setPrototypeOf?Object.setPrototypeOf.bind():function t(e,r){e.__proto__=r;return e};return f(t,e)}function l(t){var e=v();return function r(){var n=y(t),i;if(e){var a=y(this).constructor;i=Reflect.construct(n,arguments,a)}else{i=n.apply(this,arguments)}return c(this,i)}}function c(t,e){if(e&&(typeof e==="object"||typeof e==="function")){return e}else if(e!==void 0){throw new TypeError("Derived constructors may only return object or undefined")}return h(t)}function h(t){if(t===void 0){throw new ReferenceError("this hasn't been initialised - super() hasn't been called")}return t}function v(){if(typeof Reflect==="undefined"||!Reflect.construct)return false;if(Reflect.construct.sham)return false;if(typeof Proxy==="function")return true;try{Boolean.prototype.valueOf.call(Reflect.construct(Boolean,[],function(){}));return true}catch(t){return false}}function y(t){y=Object.setPrototypeOf?Object.getPrototypeOf.bind():function t(e){return e.__proto__||Object.getPrototypeOf(e)};return y(t)}function p(t,e,r){if(e in t){Object.defineProperty(t,e,{value:r,enumerable:true,configurable:true,writable:true})}else{t[e]=r}return t}
/*!
   * SAPUI5

		(c) Copyright 2009-2021 SAP SE. All rights reserved
	
   */var b=t["ResultSetItem"];var d=e["generateGuid"];var g=function(t){s(n,t);var e=l(n);function n(t){var r,i,u;var o;a(this,n);o=e.call(this,t);p(h(o),"score",0);o.dataSource=(r=t.dataSource)!==null&&r!==void 0?r:o.dataSource;o.setAttributes(t.attributes||[]);o.setTitleAttributes(t.titleAttributes);o.setTitleDescriptionAttributes(t.titleDescriptionAttributes);o.setDetailAttributes(t.detailAttributes);o.setDefaultNavigationTarget(t.defaultNavigationTarget);o.setNavigationTargets(t.navigationTargets||[]);o.score=(i=t.score)!==null&&i!==void 0?i:o.score;o.hierarchyNodePaths=(u=t.hierarchyNodePaths)!==null&&u!==void 0?u:o.hierarchyNodePaths;return o}o(n,[{key:"setDefaultNavigationTarget",value:function t(e){if(!e){this.defaultNavigationTarget=undefined;return}this.defaultNavigationTarget=e;e.parent=this}},{key:"setNavigationTargets",value:function t(e){this.navigationTargets=[];if(!e){return}var n=r(e),i;try{for(n.s();!(i=n.n()).done;){var a=i.value;this.addNavigationTarget(a)}}catch(t){n.e(t)}finally{n.f()}}},{key:"addNavigationTarget",value:function t(e){this.navigationTargets.push(e);e.parent=this}},{key:"setAttributes",value:function t(e){this.attributes=[];this.attributesMap={};var n=r(e),i;try{for(n.s();!(i=n.n()).done;){var a=i.value;this.attributes.push(a);this.attributesMap[a.id]=a;a.parent=this}}catch(t){n.e(t)}finally{n.f()}}},{key:"setTitleAttributes",value:function t(e){this.titleAttributes=[];if(!Array.isArray(e)||e.length<1){return this}for(var r=0;r<e.length;r++){var n=e[r];n.parent=this;this.titleAttributes.push(n)}return this}},{key:"setTitleDescriptionAttributes",value:function t(e){this.titleDescriptionAttributes=[];if(!Array.isArray(e)||e.length<1){return this}for(var r=0;r<e.length;r++){var n=e[r];n.parent=this;this.titleDescriptionAttributes.push(n)}return this}},{key:"setDetailAttributes",value:function t(e){this.detailAttributes=[];if(!Array.isArray(e)||e.length<1){return this}for(var r=0;r<e.length;r++){var n=e[r];n.parent=this;this.detailAttributes.push(n)}return this}},{key:"key",get:function t(){var e=[];e.push(this.dataSource.id);var n=r(this.titleAttributes),i;try{for(n.s();!(i=n.n()).done;){var a=i.value;var u=a.getSubAttributes();var o=r(u),s;try{for(o.s();!(s=o.n()).done;){var f=s.value;e.push(f.value)}}catch(t){o.e(t)}finally{o.f()}}}catch(t){n.e(t)}finally{n.f()}if(e.length===1){e.push(d())}return e.join("-")}},{key:"toString",value:function t(){var e;var r=[];var n=[];for(e=0;e<this.titleAttributes.length;++e){var i=this.titleAttributes[e];n.push(i.toString())}r.push("--"+n.join(" "));for(e=0;e<this.detailAttributes.length;++e){var a=this.detailAttributes[e];r.push(a.toString())}return r.join("\n")}}]);return n}(b);var A={__esModule:true};A.SearchResultSetItem=g;return A})})();
//# sourceMappingURL=SearchResultSetItem.js.map